DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS clicks;

CREATE TABLE urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_url TEXT NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0,
    ip TEXT NOT NULL
);

CREATE TABLE clicks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip TEXT NOT NULL
)